"""
seed_db.py — Normalise product JSON and upsert into Supabase.

Usage:
  python viewer/seed_db.py --source elmes

Requires:
  - viewer/.env with SUPABASE_URL and SUPABASE_SERVICE_KEY
  - viewer/asset_manifest.json (generated by upload_assets.py)
"""

import os
import re
import sys
import json
import argparse
from pathlib import Path

from dotenv import load_dotenv
from supabase import create_client

HERE = Path(__file__).parent
ROOT = HERE.parent

load_dotenv(HERE / ".env")

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_SERVICE_KEY"]

MANIFEST_PATH = HERE / "asset_manifest.json"

SOURCE_JSON = {
    "elmes":      ROOT / "output" / "elmes"      / "products.json",
    "sugatsune":  ROOT / "output" / "sugatsune"  / "products.json",
    "simonswerk": ROOT / "output" / "simonswerk" / "products.json",
}


# ─── Helpers ──────────────────────────────────────────────────────────────────

def parse_numeric(value) -> float | None:
    if not value:
        return None
    m = re.search(r"[\d.]+", str(value))
    return float(m.group()) if m else None


def split_paths(value: str | None) -> list[str]:
    if not value:
        return []
    return [p.strip() for p in value.split(";") if p.strip()]


_IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".gif", ".webp"}

def split_drawing_files(paths: list[str]) -> tuple[list[str], list[str]]:
    """Return (image_paths, cad_paths) split by file extension."""
    imgs, cad = [], []
    for p in paths:
        fname = p.replace("\\", "/").split("/")[-1]
        ext = fname.rsplit(".", 1)
        suffix = ("." + ext[-1]).lower() if len(ext) > 1 else ""
        if suffix in _IMAGE_EXTS:
            imgs.append(p)
        else:
            cad.append(p)
    return imgs, cad


def filter_by_model(paths: list[str], model: str) -> list[str]:
    """Keep only files whose filename contains the model identifier."""
    if not model:
        return paths
    slug = re.sub(r"[^a-z0-9]", "", model.lower())
    result = []
    for p in paths:
        fname = p.replace("\\", "/").split("/")[-1]
        fname_slug = re.sub(r"[^a-z0-9]", "", fname.lower())
        if slug in fname_slug:
            result.append(p)
    return result


def resolve_urls(filenames: list[str], prefix: str, manifest: dict) -> list[str]:
    urls = []
    for f in filenames:
        f_norm = f.replace("\\", "/")
        # If the filename already contains a path, use it directly under output/
        if "/" in f_norm:
            key = f"output/{f_norm}"
            if key in manifest:
                urls.append(manifest[key])
                continue
        # Standard: prefix + bare filename
        key_fwd = f"output/{prefix}/{f_norm}"
        key_bak = key_fwd.replace("/", "\\")
        if key_fwd in manifest:
            urls.append(manifest[key_fwd])
        elif key_bak in manifest:
            urls.append(manifest[key_bak])
        else:
            # Fallback: match by filename alone
            fname = f_norm.split("/")[-1]
            for k, v in manifest.items():
                if k.replace("\\", "/").endswith("/" + fname):
                    urls.append(v)
                    break
    return urls


# ─── Source-specific normalisers ──────────────────────────────────────────────

def normalise_elmes(record: dict, manifest: dict) -> dict:
    model    = record.get("Model", "")
    material = record.get("Material & Finish", "")
    # Split material from finish on comma if present
    mat_parts = material.split(",", 1)
    mat  = mat_parts[0].strip() if mat_parts else material
    finish = mat_parts[1].strip() if len(mat_parts) > 1 else None

    image_files   = split_paths(record.get("Images", ""))
    drawing_files = split_paths(record.get("Drawings", ""))
    drawing_imgs, drawing_cad = split_drawing_files(drawing_files)

    image_urls   = (resolve_urls(image_files,    "elmes/images",    manifest) +
                    resolve_urls(drawing_imgs,   "elmes/drawings",  manifest))
    drawing_urls = resolve_urls(drawing_cad, "elmes/drawings", manifest)

    return {
        "id":           f"artunion:{model}",
        "source":       "artunion",
        "brand":        "ELMES",
        "model":        model,
        "name":         record.get("Name"),
        "category":     record.get("Category"),
        "subcategory":  record.get("Subcategory"),
        "material":     mat or None,
        "finish":       finish,
        "load_capacity_kg":  None,
        "door_height_mm":    None,
        "door_width_mm":     None,
        "door_thickness_mm": None,
        "spec_pdf_url":  None,
        "drawing_urls":  drawing_urls,
        "image_urls":    image_urls,
        "source_url":    record.get("URL"),
        "raw":           record,
    }


def normalise_sugatsune(record: dict, manifest: dict) -> dict:
    model = record.get("Series Model", record.get("Model", ""))
    item  = record.get("Item Code", model)
    uid   = f"sugatsune:{item}"

    image_files   = split_paths(record.get("Item Image", ""))
    pdf_files     = split_paths(record.get("Spec Sheet PDF", ""))
    drawing_files = filter_by_model(split_paths(record.get("Drawings", "")), model)
    drawing_imgs, drawing_cad = split_drawing_files(drawing_files)

    image_urls   = (resolve_urls(image_files,   "sugatsune/images/items", manifest) +
                    resolve_urls(drawing_imgs,  "sugatsune/drawings",     manifest))
    drawing_urls = resolve_urls(drawing_cad, "sugatsune/drawings", manifest)

    spec_pdf_url = None
    if pdf_files:
        pdfs = resolve_urls(pdf_files, "sugatsune/specs", manifest)
        spec_pdf_url = pdfs[0] if pdfs else None

    return {
        "id":           uid,
        "source":       "sugatsune",
        "brand":        "Sugatsune",
        "model":        model,
        "name":         record.get("Item Name", item),
        "category":     record.get("Category"),
        "subcategory":  record.get("Subcategory"),
        "material":     record.get("Material"),
        "finish":       record.get("Finish"),
        "load_capacity_kg":  None,
        "door_height_mm":    parse_numeric(record.get("Height H")),
        "door_width_mm":     None,
        "door_thickness_mm": parse_numeric(record.get("Thickness D (mm)")),
        "spec_pdf_url":  spec_pdf_url,
        "drawing_urls":  drawing_urls,
        "image_urls":    image_urls,
        "source_url":    record.get("Series URL"),
        "raw":           record,
    }


def normalise_simonswerk(record: dict, manifest: dict) -> dict:
    model = record.get("Model", "")
    slug  = record.get("Slug", model)
    finish_code = re.sub(r"[^a-z0-9]+", "-", (record.get("Finish Code") or "").lower()).strip("-")
    uid   = f"simonswerk:{slug}:{finish_code}" if finish_code else f"simonswerk:{slug}"

    hero_files    = split_paths(record.get("Hero Image", ""))
    finish_files  = split_paths(record.get("Finish Image", ""))
    cad_files     = split_paths(record.get("CAD Drawings (DXF)", ""))
    drawing_files = split_paths(record.get("Drawings", ""))
    pdf_files     = split_paths(record.get("Installation PDF", ""))

    cad_imgs, cad_only = split_drawing_files(cad_files)
    drawing_imgs, _    = split_drawing_files(drawing_files)
    image_urls   = (
        resolve_urls(finish_files,  "simonswerk/images/finish",    manifest) +
        resolve_urls(hero_files,    "simonswerk/images/hero",      manifest) +
        resolve_urls(drawing_imgs,  "simonswerk/images/drawings",  manifest) +
        resolve_urls(cad_imgs,      "simonswerk/cad",              manifest)
    )
    drawing_urls = resolve_urls(cad_only, "simonswerk/cad", manifest)
    spec_pdf_url = None
    if pdf_files:
        pdfs = resolve_urls(pdf_files, "simonswerk/docs", manifest)
        spec_pdf_url = pdfs[0] if pdfs else None

    return {
        "id":           uid,
        "source":       "simonswerk",
        "brand":        record.get("Brand", "Simonswerk"),
        "model":        model,
        "name":         record.get("Subtitle", model),
        "category":     record.get("Type of Door Leaf"),
        "subcategory":  record.get("Type of Frame"),
        "material":     None,
        "finish":       record.get("Finish Name"),
        "load_capacity_kg":  parse_numeric(record.get("Load Capacity")),
        "door_height_mm":    None,
        "door_width_mm":     None,
        "door_thickness_mm": None,
        "spec_pdf_url":  spec_pdf_url,
        "drawing_urls":  drawing_urls,
        "image_urls":    image_urls,
        "source_url":    record.get("Product URL"),
        "raw":           record,
    }


NORMALISERS = {
    "elmes":      normalise_elmes,
    "sugatsune":  normalise_sugatsune,
    "simonswerk": normalise_simonswerk,
}


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description="Seed Supabase with product data")
    ap.add_argument("--source", required=True, choices=list(NORMALISERS))
    ap.add_argument("--batch-size", type=int, default=500)
    ap.add_argument("--dry-run", action="store_true", help="Print rows without inserting")
    args = ap.parse_args()

    json_path = SOURCE_JSON[args.source]
    if not json_path.exists():
        print(f"ERROR: {json_path} not found", file=sys.stderr)
        sys.exit(1)

    if not MANIFEST_PATH.exists():
        print("ERROR: asset_manifest.json not found — run upload_assets.py first", file=sys.stderr)
        sys.exit(1)

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    records  = json.loads(json_path.read_text(encoding="utf-8"))

    normalise = NORMALISERS[args.source]
    rows_raw = [normalise(r, manifest) for r in records]
    # Deduplicate by id — keep last occurrence (most complete record)
    seen = {}
    for r in rows_raw:
        seen[r["id"]] = r
    rows = list(seen.values())

    print(f"Loaded {len(rows_raw)} records from {json_path} ({len(rows)} unique after dedup)")

    if args.dry_run:
        print(json.dumps(rows[:3], indent=2, ensure_ascii=False, default=str))
        print(f"Dry run — {len(rows)} rows would be upserted.")
        return

    client = create_client(SUPABASE_URL, SUPABASE_KEY)
    total = 0
    for i in range(0, len(rows), args.batch_size):
        batch = rows[i : i + args.batch_size]
        client.table("products").upsert(batch).execute()
        total += len(batch)
        print(f"  upserted {total}/{len(rows)}")

    print(f"Done. {total} rows upserted for source={args.source}.")


if __name__ == "__main__":
    main()
