"""
seed_db.py — Normalise product JSON and upsert into Supabase.

Usage:
  python viewer/seed_db.py --source elmes

Requires:
  - viewer/.env with SUPABASE_URL and SUPABASE_SERVICE_KEY
  - viewer/asset_manifest.json (generated by upload_assets.py)
"""

import os
import re
import sys
import json
import argparse
from pathlib import Path

from dotenv import load_dotenv
from supabase import create_client

HERE = Path(__file__).parent
ROOT = HERE.parent

load_dotenv(HERE / ".env")

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_SERVICE_KEY"]

MANIFEST_PATH = HERE / "asset_manifest.json"

SOURCE_JSON = {
    "elmes":      ROOT / "output" / "elmes"      / "products.json",
    "sugatsune":  ROOT / "output" / "sugatsune"  / "products.json",
    "simonswerk": ROOT / "output" / "simonswerk" / "products.json",
}


# ─── Helpers ──────────────────────────────────────────────────────────────────

def parse_numeric(value) -> float | None:
    if not value:
        return None
    m = re.search(r"[\d.]+", str(value))
    return float(m.group()) if m else None


def split_paths(value: str | None) -> list[str]:
    if not value:
        return []
    return [p.strip() for p in value.split(";") if p.strip()]


def resolve_urls(filenames: list[str], prefix: str, manifest: dict) -> list[str]:
    urls = []
    for f in filenames:
        key = f"output/{prefix}/{f}"
        if key in manifest:
            urls.append(manifest[key])
        else:
            # fallback: also try without subdirectory nesting
            for k, v in manifest.items():
                if k.endswith("/" + f):
                    urls.append(v)
                    break
    return urls


# ─── Source-specific normalisers ──────────────────────────────────────────────

def normalise_elmes(record: dict, manifest: dict) -> dict:
    model    = record.get("Model", "")
    material = record.get("Material & Finish", "")
    # Split material from finish on comma if present
    mat_parts = material.split(",", 1)
    mat  = mat_parts[0].strip() if mat_parts else material
    finish = mat_parts[1].strip() if len(mat_parts) > 1 else None

    image_files   = split_paths(record.get("Images", ""))
    drawing_files = split_paths(record.get("Drawings", ""))

    image_urls   = resolve_urls(image_files,   "elmes/images",   manifest)
    drawing_urls = resolve_urls(drawing_files, "elmes/drawings", manifest)

    return {
        "id":           f"artunion:{model}",
        "source":       "artunion",
        "brand":        "ELMES",
        "model":        model,
        "name":         record.get("Name"),
        "category":     record.get("Category"),
        "subcategory":  record.get("Subcategory"),
        "material":     mat or None,
        "finish":       finish,
        "load_capacity_kg":  None,
        "door_height_mm":    None,
        "door_width_mm":     None,
        "door_thickness_mm": None,
        "spec_pdf_url":  None,
        "drawing_urls":  drawing_urls,
        "image_urls":    image_urls,
        "source_url":    record.get("URL"),
        "raw":           record,
    }


def normalise_sugatsune(record: dict, manifest: dict) -> dict:
    model = record.get("Series Model", record.get("Model", ""))
    item  = record.get("Item Code", model)
    uid   = f"sugatsune:{item}"

    image_files = split_paths(record.get("Item Image", ""))
    series_imgs = split_paths(record.get("Series Images", ""))
    pdf_files   = split_paths(record.get("Spec Sheet PDF", ""))

    image_urls  = (
        resolve_urls(image_files,  "sugatsune/images/items",  manifest) +
        resolve_urls(series_imgs,  "sugatsune/images/series", manifest)
    )
    spec_pdf_url = None
    if pdf_files:
        pdfs = resolve_urls(pdf_files, "sugatsune/specs", manifest)
        spec_pdf_url = pdfs[0] if pdfs else None

    return {
        "id":           uid,
        "source":       "sugatsune",
        "brand":        "Sugatsune",
        "model":        model,
        "name":         record.get("Name", item),
        "category":     record.get("Category"),
        "subcategory":  record.get("Subcategory"),
        "material":     record.get("Material"),
        "finish":       record.get("Finish"),
        "load_capacity_kg":  None,
        "door_height_mm":    parse_numeric(record.get("Height")),
        "door_width_mm":     None,
        "door_thickness_mm": parse_numeric(record.get("Thickness")),
        "spec_pdf_url":  spec_pdf_url,
        "drawing_urls":  [],
        "image_urls":    image_urls,
        "source_url":    record.get("URL"),
        "raw":           record,
    }


def normalise_simonswerk(record: dict, manifest: dict) -> dict:
    model = record.get("Model", "")
    slug  = record.get("Slug", model)
    uid   = f"simonswerk:{slug}"

    hero_files   = split_paths(record.get("Hero Image", ""))
    finish_files = split_paths(record.get("Finish Image", ""))
    cad_files    = split_paths(record.get("CAD Drawings", ""))
    pdf_files    = split_paths(record.get("Installation PDF", ""))

    image_urls   = (
        resolve_urls(hero_files,   "simonswerk/images/hero",   manifest) +
        resolve_urls(finish_files, "simonswerk/images/finish", manifest)
    )
    drawing_urls = resolve_urls(cad_files, "simonswerk/cad", manifest)
    spec_pdf_url = None
    if pdf_files:
        pdfs = resolve_urls(pdf_files, "simonswerk/docs/installation", manifest)
        spec_pdf_url = pdfs[0] if pdfs else None

    return {
        "id":           uid,
        "source":       "simonswerk",
        "brand":        record.get("Brand", "Simonswerk"),
        "model":        model,
        "name":         record.get("Name", model),
        "category":     record.get("Category"),
        "subcategory":  record.get("Subcategory"),
        "material":     None,
        "finish":       record.get("Finish"),
        "load_capacity_kg":  parse_numeric(record.get("Load Capacity")),
        "door_height_mm":    None,
        "door_width_mm":     None,
        "door_thickness_mm": None,
        "spec_pdf_url":  spec_pdf_url,
        "drawing_urls":  drawing_urls,
        "image_urls":    image_urls,
        "source_url":    record.get("URL"),
        "raw":           record,
    }


NORMALISERS = {
    "elmes":      normalise_elmes,
    "sugatsune":  normalise_sugatsune,
    "simonswerk": normalise_simonswerk,
}


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description="Seed Supabase with product data")
    ap.add_argument("--source", required=True, choices=list(NORMALISERS))
    ap.add_argument("--batch-size", type=int, default=500)
    ap.add_argument("--dry-run", action="store_true", help="Print rows without inserting")
    args = ap.parse_args()

    json_path = SOURCE_JSON[args.source]
    if not json_path.exists():
        print(f"ERROR: {json_path} not found", file=sys.stderr)
        sys.exit(1)

    if not MANIFEST_PATH.exists():
        print("ERROR: asset_manifest.json not found — run upload_assets.py first", file=sys.stderr)
        sys.exit(1)

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    records  = json.loads(json_path.read_text(encoding="utf-8"))

    normalise = NORMALISERS[args.source]
    rows = [normalise(r, manifest) for r in records]

    print(f"Loaded {len(rows)} records from {json_path}")

    if args.dry_run:
        print(json.dumps(rows[:3], indent=2, ensure_ascii=False, default=str))
        print(f"Dry run — {len(rows)} rows would be upserted.")
        return

    client = create_client(SUPABASE_URL, SUPABASE_KEY)
    total = 0
    for i in range(0, len(rows), args.batch_size):
        batch = rows[i : i + args.batch_size]
        client.table("products").upsert(batch).execute()
        total += len(batch)
        print(f"  upserted {total}/{len(rows)}")

    print(f"Done. {total} rows upserted for source={args.source}.")


if __name__ == "__main__":
    main()
